/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.staffView;

import controller.MenuController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Staff;

/**
 *
 * @author Trinh
 */
public class StaffView extends javax.swing.JPanel {

    private MenuController controller;

    public StaffView() {
        initComponents();
        controller = new MenuController(staffView);
        controller.setViewStaff(new JButton());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffView = new javax.swing.JPanel();
        staffMenu = new javax.swing.JPanel();
        addStaffBtn = new javax.swing.JButton();
        fixStaffBtn = new javax.swing.JButton();
        delStaffBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        javax.swing.GroupLayout staffViewLayout = new javax.swing.GroupLayout(staffView);
        staffView.setLayout(staffViewLayout);
        staffViewLayout.setHorizontalGroup(
            staffViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        staffViewLayout.setVerticalGroup(
            staffViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        addStaffBtn.setText("Thêm Nhân Viên");
        addStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffBtnActionPerformed(evt);
            }
        });

        fixStaffBtn.setText("Sửa Nhân Viên");
        fixStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixStaffBtnActionPerformed(evt);
            }
        });

        delStaffBtn.setText("Xoá Nhân Viên");

        backBtn.setText("Trở Lại");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffMenuLayout = new javax.swing.GroupLayout(staffMenu);
        staffMenu.setLayout(staffMenuLayout);
        staffMenuLayout.setHorizontalGroup(
            staffMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(addStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(fixStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(delStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        staffMenuLayout.setVerticalGroup(
            staffMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(staffMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffBtn)
                    .addComponent(fixStaffBtn)
                    .addComponent(delStaffBtn)
                    .addComponent(backBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staffView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staffMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staffView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBtnActionPerformed
        controller.setViewStaff(addStaffBtn);
    }//GEN-LAST:event_addStaffBtnActionPerformed

    private void fixStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixStaffBtnActionPerformed
        Staff c = DefaultStaffView.getStaffSelected();
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Nhân Viên Cần Sửa Thông Tin", "Thông Báo", JOptionPane.ERROR_MESSAGE);
        } else {
            controller.setViewStaff(fixStaffBtn);
        }
    }//GEN-LAST:event_fixStaffBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        controller.setViewStaff(backBtn);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton delStaffBtn;
    private javax.swing.JButton fixStaffBtn;
    private javax.swing.JPanel staffMenu;
    private javax.swing.JPanel staffView;
    // End of variables declaration//GEN-END:variables
}
