/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import service.MenuController;

/**
 *
 * @author Admin
 */
public class MenuFrame extends javax.swing.JFrame {

    public MenuController controler;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        GraphicsEnvironment graphics
                = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice device = graphics.getDefaultScreenDevice();
        JFrame frame = new JFrame("Fullscreen");
        JPanel panel = new JPanel();
        JLabel label = new JLabel("", JLabel.CENTER);
        label.setText("This is in fullscreen mode!");
        label.setOpaque(true);
        frame.add(panel);
        frame.add(label);
        frame.setUndecorated(true);
        frame.setResizable(false);
        device.setFullScreenWindow(frame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
