package view.WareHouseView;

import controller.*;
import java.awt.Color;
import java.awt.*;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class AddWareHouseView extends javax.swing.JFrame {

    private WareHouseService ws;
    private Label message;


    public AddWareHouseView() {
         ws = new WareHouseService();
        initComponents();
    }

    private void ActionPerformed(java.awt.event.ActionEvent evt) {
        int ma_kho_hang = Integer.parseInt(textWid.getText());
        String ten_san_pham = textWname.getText();
        //Date ngay_nhap = Date.parseDate(textWDayin.getName());
        int so_luong = Integer.parseInt(textWquantity.getText());
        Double gia_nhap = Double.parseDouble(textWpricein.getText());
        Double gia_ban = Double.parseDouble(textWpriceout.getText());
        //Date han_su_dung = Date.parseDate(textWhsd.getText());

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date parsedDate;

        try {
            parsedDate = dateFormat.parse(textWDayin.getText());
            Date ngay_nhap = new Date(parsedDate.getTime());

            parsedDate = dateFormat.parse(textWhsd.getText());
            Date han_su_dung = new Date(parsedDate.getTime());

            // Rest of your code...
            boolean check = ws.createWareHouse(ten_san_pham, ngay_nhap, so_luong, gia_nhap, gia_ban, han_su_dung);
            if (check) {
                message.setForeground(new Color(13, 110, 253));
                message.setText("Thêm Khách Hàng Thành Công");
            } else {
                message.setForeground(new Color(255, 0, 0));
                message.setText("Thêm Khách Hàng Thất Bại");
            }
        } catch (ParseException e) {
            e.printStackTrace();
            return; // Exit the method or handle the error appropriately
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddKhoHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddWH = new javax.swing.JButton();
        textWid = new javax.swing.JTextField();
        textWname = new javax.swing.JTextField();
        textWDayin = new javax.swing.JTextField();
        textWquantity = new javax.swing.JTextField();
        textWpricein = new javax.swing.JTextField();
        textWpriceout = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textWhsd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma Kho Hang");

        jLabel2.setText("Ten San Pham");

        jLabel3.setText("Ngay Nhap");

        jLabel4.setText("So Luong");

        jLabel6.setText("Gia Ban");

        jLabel7.setText("Han Su Dung");

        AddWH.setText("Them Ma Hang");

        textWname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWnameActionPerformed(evt);
            }
        });

        textWDayin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWDayinActionPerformed(evt);
            }
        });

        textWquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWquantityActionPerformed(evt);
            }
        });

        textWpriceout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWpriceoutActionPerformed(evt);
            }
        });

        jLabel8.setText("Gia Nhap ");

        javax.swing.GroupLayout AddKhoHangLayout = new javax.swing.GroupLayout(AddKhoHang);
        AddKhoHang.setLayout(AddKhoHangLayout);
        AddKhoHangLayout.setHorizontalGroup(
            AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddKhoHangLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddKhoHangLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AddKhoHangLayout.createSequentialGroup()
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)))
                        .addGap(495, 1018, Short.MAX_VALUE))))
            .addGroup(AddKhoHangLayout.createSequentialGroup()
                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddKhoHangLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(AddWH, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddKhoHangLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddKhoHangLayout.createSequentialGroup()
                                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(125, 125, 125)
                                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textWname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textWid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddKhoHangLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(139, 139, 139)
                                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textWpricein, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textWDayin)
                                        .addComponent(textWquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                    .addComponent(textWpriceout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textWhsd, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddKhoHangLayout.setVerticalGroup(
            AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddKhoHangLayout.createSequentialGroup()
                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddKhoHangLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textWid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(textWname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(textWDayin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textWquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddKhoHangLayout.createSequentialGroup()
                        .addGap(0, 265, Short.MAX_VALUE)
                        .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textWpricein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textWpriceout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AddKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textWhsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addComponent(AddWH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(AddKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(AddKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1287, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void textWnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWnameActionPerformed

    private void textWpriceoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWpriceoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWpriceoutActionPerformed

    private void textWDayinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWDayinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWDayinActionPerformed

    private void textWquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWquantityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddKhoHang;
    private javax.swing.JButton AddWH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textWDayin;
    private javax.swing.JTextField textWhsd;
    private javax.swing.JTextField textWid;
    private javax.swing.JTextField textWname;
    private javax.swing.JTextField textWpricein;
    private javax.swing.JTextField textWpriceout;
    private javax.swing.JTextField textWquantity;
    // End of variables declaration//GEN-END:variables
}
